### ISSUE TITLE
Use $wgLogo instead of hard-coding

### ISSUE THREAD

**Issue by samwilson** [osmfoundation/osmf-mediawiki-skin#23]
The logo path is currently being hard-coded to `skins/OSMFoundation/img/logo.png`, this should instead use the [$wgLogo](https://www.mediawiki.org/wiki/Manual:$wgLogo) configuration variable. Then this skin would be more usable by more sites (e.g. https://phabricator.miraheze.org/T3337 ).

**Comment by nebulon42** [comment]
Thanks for raising this issue here. Thing is that this theme is not really meant to be reused by others hence I did not pay attention to make it reusable. The theme is public because at OSM we value openness highly. I'm not categorically against it being reused, but I'm not sure I'd like to put effort into supporting other use cases. I will consult with others on what our stance on reusing this theme is and report back here.

**Comment by samwilson** [comment]
Thanks @nebulon42 that makes sense.

**Comment by jdlrobson** [comment]
This should be fixed now.

**Comment by samwilson** [comment]
Great!

The logo is still in the repo, and mentioned in README.md, so probably this is still not quite ready for re-use elsewhere.
